package com.example.constantin.avonotifier.impl.just;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 09/10/2016
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class AAKArrayOfDosarSedinta extends Vector< AAKDosarSedinta> implements KvmSerializable
{
    
    public AAKArrayOfDosarSedinta(){}
    
    public AAKArrayOfDosarSedinta(java.lang.Object inObj,AAKExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            java.lang.Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                AAKDosarSedinta j1= (AAKDosarSedinta)__envelope.get(j,AAKDosarSedinta.class,false);
                add(j1);
            }
        }
}
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "DosarSedinta";
        info.type = AAKDosarSedinta.class;
    	info.namespace= "portalquery.just.ro";
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

    
}