package com.example.constantin.avonotifier.impl.just;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 09/10/2016
//
//---------------------------------------------------



public interface AAKIServiceEvents
{
    public void Starting();
    public void Completed(AAKOperationResult result);
}
